name: Test CI

on:
  workflow_dispatch:
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout our Code
        uses: actions/checkout@v2

      - name: Get and setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Check Java Version
        run: java -version

      - name: Run Tests
        run: mvn test

  key-test:
    runs-on: windows-latest

    steps:
      - name: check key connection
        run: echo ${{ secrets.KEY }}

      - name: calculate numbers
        run: set /a 2+2

      - name: calculate number with key
        run: set /a ${{ secrets.KEY }}+2