name: Test CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout our Code
        uses: actions/checkout@v2

      - name: Get and setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Check Java Version
        run: java -version

      - name: Run Tests
        run: mvn test